/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Photo = IDL.Vec(IDL.Nat8);
export const MemoryId = IDL.Nat;
export const Author = IDL.Principal;
export const Time = IDL.Int;
export const Memory = IDL.Record({
  'id' : MemoryId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : Author,
  'timestamp' : Time,
  'photo' : IDL.Opt(Photo),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createMemory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(Photo)],
      [MemoryId],
      [],
    ),
  'deleteMemory' : IDL.Func([MemoryId], [], []),
  'getAllMemories' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
  'getMemory' : IDL.Func([MemoryId], [IDL.Opt(Memory)], ['query']),
  'updateMemory' : IDL.Func(
      [MemoryId, IDL.Text, IDL.Text, IDL.Opt(Photo)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Photo = IDL.Vec(IDL.Nat8);
  const MemoryId = IDL.Nat;
  const Author = IDL.Principal;
  const Time = IDL.Int;
  const Memory = IDL.Record({
    'id' : MemoryId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : Author,
    'timestamp' : Time,
    'photo' : IDL.Opt(Photo),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createMemory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(Photo)],
        [MemoryId],
        [],
      ),
    'deleteMemory' : IDL.Func([MemoryId], [], []),
    'getAllMemories' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
    'getMemory' : IDL.Func([MemoryId], [IDL.Opt(Memory)], ['query']),
    'updateMemory' : IDL.Func(
        [MemoryId, IDL.Text, IDL.Text, IDL.Opt(Photo)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };